project:
  type: book
  output-dir: _book

book:
  title: "Practice Notebook"
  author: "Sara M Schaal"
  date: last-modified
  chapters:
    - index.qmd
    - 01-PCAs.qmd
    - 02-FSTOutliers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

